version: '3.8'
services:
  next-app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - next-app
